### ISSUE TITLE
建议出一下docker挂载启动教程

### ISSUE THREAD

**Issue by jaychoubaby** [lollipopkit/server_box_monitor#11]
我两台服务器配置一弄一样，一台使用挂载命令启动
`docker run -d -v /proc:/proc --network=host --name=srvbox -p 3770:3770 lollipopkit/srvbox_monitor `

得到结果如下：
`{
code: 0,
data: {
cpu: "3.6%",
disk: "26.0g / 39.0g",
mem: "777.8m / 803.8m",
name: "Server 1",
net: "31.7g / 28.8g"
}
}`

另外一台docker compose启动，结果如下：
`{
code: 0,
data: {
cpu: "2.0%",
disk: "25.8g / 39.0g",
mem: "715.7m / 803.8m",
name: "jay",
net: "27.0k / 17.7k"
}
}`

可以看到磁盘大小监控指标正常，但是net指标差别很大，另外，通过其他工具检测出mem指标也差别很大，
![image](https://github.com/lollipopkit/server_box_monitor/assets/26641387/da93a8b4-b86b-4404-9d3d-ec3cab2af2d7)

使用golang安装失败了，感觉还是docker部署最直接，但是就像前面说的，docker如果不挂载启动最终得到的结果不正确，另外我发现其他应用的部署命令里面是带有挂载命令的，可以参考一下
`docker run -d \
  -v /proc:/proc \
  --privileged=true \
  --restart unless-stopped \
  --network=host \
  --name=serverbee-web \
  zingerbee/serverbee-web -p 9527`

**Comment by jaychoubaby** [comment]
另外 自行编辑docker run的执行，还不知道config.json 要挂载到哪里，所以导致没有配置，迫切需要出个教程，谢谢

**Comment by lollipopkit** [comment]
![image](https://github.com/lollipopkit/server_box_monitor/assets/10864310/d82998d3-68c3-4801-966c-6feb06ea6e96)
我是这样挂载的，然后就可以通过容器内的 `/host_mark/Users/lolli/docker` `/root/.config/server_box` 获取宿主机的硬盘信息

**Comment by jaychoubaby** [comment]
> ![image](https://user-images.githubusercontent.com/10864310/258307297-d82998d3-68c3-4801-966c-6feb06ea6e96.png) 我是这样挂载的，然后就可以通过容器内的 `/host_mark/Users/lolli/docker` `/root/.config/server_box` 获取宿主机的硬盘信息（将 监控规则的 `matcher` 设置为上述路径二选一）

可是宿主机根目录下找不到config目录，挂载proc确实大部分数据都能对上了
