### ISSUE TITLE
mem数据不对

### ISSUE THREAD

**Issue by jaychoubaby** [lollipopkit/server_box_monitor#12]
已经挂载proc目录安装，web得到结果：
`{
code: 0,
data: {
cpu: "2.6%",
disk: "25.8g / 39.0g",
mem: "788.2m / 803.8m",
name: "jay",
net: "7.8k / 2.4k"
}
}`

容器内得到结果：
`              total        used        free      shared  buff/cache   available
Mem:         803.8M      545.0M       28.4M       10.7M      230.4M      232.5M
Swap:          8.0G      957.5M        7.1G`

宿主机结果：
`              total        used        free      shared  buff/cache   available
Mem:          803Mi       555Mi        49Mi        10Mi       199Mi       222Mi
Swap:         8.0Gi       957Mi       7.1Gi`

可见api返回数据错误

**Comment by jaychoubaby** [comment]
api返回的结果建议可以多一点，把检测数据全都返回吧

**Comment by lollipopkit** [comment]
sbm 使用 `cat /proc/meminfo` 获取内存信息，麻烦执行并粘贴结果

**Comment by jaychoubaby** [comment]
> sbm 使用 `cat /proc/meminfo` 获取内存信息，麻烦执行并粘贴结果

宿主机：
MemTotal:         823108 kB
MemFree:           40636 kB
MemAvailable:     255772 kB
Buffers:              24 kB
Cached:           189208 kB
SwapCached:       133184 kB
Active:           252568 kB
Inactive:         216492 kB
Active(anon):     137596 kB
Inactive(anon):   143992 kB
Active(file):     114972 kB
Inactive(file):    72500 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       8388604 kB
SwapFree:        7392376 kB
Dirty:                16 kB
Writeback:             0 kB
AnonPages:        276712 kB
Mapped:            79220 kB
Shmem:              1760 kB
KReclaimable:      43708 kB
Slab:             128276 kB
SReclaimable:      43708 kB
SUnreclaim:        84568 kB
KernelStack:        8112 kB
PageTables:        21008 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     8800156 kB
Committed_AS:    4423804 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
Percpu:             1544 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      818064 kB
DirectMap2M:      225280 kB
DirectMap1G:           0 kB

容器内：

MemTotal:         823108 kB
MemFree:           23864 kB
MemAvailable:     279212 kB
Buffers:              24 kB
Cached:           229216 kB
SwapCached:       103644 kB
Active:           235648 kB
Inactive:         249336 kB
Active(anon):     121000 kB
Inactive(anon):   136300 kB
Active(file):     114648 kB
Inactive(file):   113036 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       8388604 kB
SwapFree:        7389308 kB
Dirty:                36 kB
Writeback:             0 kB
AnonPages:        253276 kB
Mapped:            81232 kB
Shmem:              1556 kB
KReclaimable:      43708 kB
Slab:             128316 kB
SReclaimable:      43708 kB
SUnreclaim:        84608 kB
KernelStack:        8224 kB
PageTables:        21164 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     8800156 kB
Committed_AS:    4528144 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
Percpu:             1544 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      818064 kB
DirectMap2M:      225280 kB
DirectMap1G:           0 kB
