### ISSUE TITLE
配置文件位置

### ISSUE THREAD

**Issue by 0123-smallbottle** [lollipopkit/server_box_monitor#17]
開發者您好，我看了wiki，但還是找不到配置文件在哪裡，可以說一下嗎？

**Comment by lollipopkit** [comment]
- docker 安装的吗？可能得去 运行 docker run 或 储存 docker-compose 的文件夹
- 如果是 binary 安装，可能安装的用户和当前用户不一致

**Comment by 0123-smallbottle** [comment]
> * docker 安装的吗？可能得去 运行 docker run 或 储存 docker-compose 的文件夹
> * 如果是 binary 安装，可能安装的用户和当前用户不一致

我用的是一鍵安裝脚本
