### ISSUE TITLE
IOS小组件无响应 Https + 反代 （ip：3770）结尾/status

### ISSUE THREAD

**Issue by sakuraanzu** [lollipopkit/server_box_monitor#21]
IOS小组件 Url：
Https + 域名反代 （ip：3770）+结尾/status 
小组件无法获取，为白屏界面
![IMG_2326](https://github.com/lollipopkit/server_box_monitor/assets/81692273/e0bb7d3c-73be-4452-9093-6098aea91607)
反代ip是http。https+ip+端口 显示无法连接

Apple watch键入url无法在手机端保存，点击保存按钮后会清空之前刚键入的url键值，为空白页
同时手表界面信息无改变
![incoming-DFDB8EC2-7F2E-4114-8819-FFF848880A4D](https://github.com/lollipopkit/server_box_monitor/assets/81692273/edf925ec-c6ec-43e3-ba9f-8f22febb8811)

**Comment by lollipopkit** [comment]
尝试 3770 端口

**Comment by sakuraanzu** [comment]
是的，是3770端口，网页能打开

**Comment by lollipopkit** [comment]
域名填 sbm点lolli点tech 试试

**Comment by sakuraanzu** [comment]
试了下同样是白屏的情况![image](https://github.com/lollipopkit/server_box_monitor/assets/81692273/1b8f4f80-0eed-4e9f-a368-116e74669b56)
![image](https://github.com/lollipopkit/server_box_monitor/assets/81692273/82ff2921-34c4-4b60-8e51-0c841da85dd7)

**Comment by lollipopkit** [comment]
。。。b，不是 p

**Comment by sakuraanzu** [comment]
![image](https://github.com/lollipopkit/server_box_monitor/assets/81692273/9edd1081-f20e-4713-bd5a-56b4ae31c511)

**Comment by sakuraanzu** [comment]
这个是意味着正常连接吗

**Comment by lollipopkit** [comment]
意味着获取数据失败
<img width="420" alt="image" src="https://github.com/lollipopkit/server_box_monitor/assets/10864310/2683d764-1758-40d4-92a9-83a9c894c1e1">
可能是因为我套了 cf，可以开启梯子再尝试吗？

**Comment by lollipopkit** [comment]
正常结果
<img width="912" alt="image" src="https://github.com/lollipopkit/server_box_monitor/assets/10864310/e9589a9b-31c9-4faa-a7eb-f05c07142f4b">

**Comment by sakuraanzu** [comment]
![image](https://github.com/lollipopkit/server_box_monitor/assets/81692273/2ff2150c-4f39-49f5-8d7d-f1a042824990)

/status是正常的

**Comment by lollipopkit** [comment]
那应该是你服务器配置的问题了，比如 https 证书不信任

**Comment by sakuraanzu** [comment]
我也是子域名反代IP和端口（http的

网页/status可以正常访问

**Comment by lollipopkit** [comment]
发下网址看看

**Comment by lollipopkit** [comment]
。。。感谢尝试我的软件
