### ISSUE TITLE
磁盘监控服务出错

### ISSUE THREAD

**Issue by jaychoubaby** [lollipopkit/server_box_monitor#8]
服务部署之后 通过web访问数据正常如下：
`{
code: 0,
data: {
cpu: "1.9%",
disk: "25.6g / 39.0g",
mem: "686.7m / 803.8m",
name: "back",
net: "16.5k / 4.9k"
}
}`

但是docker服务日志提示报错：

[WAR] [RULE] Rule(disk >=80% /dev/sda1) error: invalid rule
disk not found: /dev/sda1

**Comment by lollipopkit** [comment]
执行 `df -h`，粘贴输出

**Comment by jaychoubaby** [comment]
> 执行 `df -h`，粘贴输出

Filesystem                     Size  Used Avail Use% Mounted on
devtmpfs                       355M     0  355M   0% /dev
tmpfs                          402M     0  402M   0% /dev/shm
tmpfs                          402M   42M  361M  11% /run
tmpfs                          402M     0  402M   0% /sys/fs/cgroup
/dev/mapper/centosvolume-root   40G   26G   14G  66% /
/dev/sda2                     1014M  602M  413M  60% /boot
/dev/sda1                      100M  7.3M   93M   8% /boot/efi
overlay                         40G   26G   14G  66% /var/lib/docker/overlay2/2e25140c8e4d7cb41e50a5ee1ff9bec57f78f4d2153a89924911f14d946e2dff/merged
overlay                         40G   26G   14G  66% /var/lib/docker/overlay2/9bb79d2a05069c0fd8b7d1ac3fecd4bde7aefc020062f8eb06b27a096874e5f2/merged
shm                             64M     0   64M   0% /var/lib/docker/containers/859a6f0583b00d476dbdb901a78ca0db43d8e32261a719612bd52275ae89b36c/mounts/shm
overlay                         40G   26G   14G  66% /var/lib/docker/overlay2/b4495c37bf40ab489499e10208e2fe8ef4e98d3d8a3782f882ab98151873601d/merged
overlay                         40G   26G   14G  66% /var/lib/docker/overlay2/5d09361f0a2a3e3827ae02cc70c3d61de0c2bf7e39c386f2005fb080adaa6906/merged
overlay                         40G   26G   14G  66% /var/lib/docker/overlay2/708565ffad7031b4d91da2b4d9a5f005ca3ce0960e7aaf0fd7bd2c2d956a69bc/merged
overlay                         40G   26G   14G  66% /var/lib/docker/overlay2/71a4db479fb5f106a4a7877476aababb2adee2fa8378197666451bc15cb76b7a/merged
tmpfs                           81M     0   81M   0% /run/user/0

**Comment by lollipopkit** [comment]
需要 docker 内执行

**Comment by jaychoubaby** [comment]
> 需要 docker 内执行，因为 docker 内外的环境不同。
> 
> 如果要监控 docker 宿主机的某个路径，要么挂载到 docker，要么直接在宿主机运行 sbm

Filesystem                Size      Used Available Use% Mounted on
overlay                  39.0G     25.5G     13.5G  65% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                   401.9M         0    401.9M   0% /sys/fs/cgroup
shm                      64.0M         0     64.0M   0% /dev/shm
/dev/mapper/centosvolume-root
                         39.0G     25.5G     13.5G  65% /etc/resolv.conf
/dev/mapper/centosvolume-root
                         39.0G     25.5G     13.5G  65% /etc/hostname
/dev/mapper/centosvolume-root
                         39.0G     25.5G     13.5G  65% /etc/hosts
/dev/mapper/centosvolume-root
                         39.0G     25.5G     13.5G  65% /root/.config/server_box
tmpfs                   401.9M         0    401.9M   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                   401.9M         0    401.9M   0% /proc/scsi
tmpfs                   401.9M         0    401.9M   0% /sys/firmware


好的 大概明白了，那其他的参数不会也都是监控的其实是docker内的指标把

**Comment by lollipopkit** [comment]
- CPU、内存：如果非 docker desktop，并且没设置容器限制，那就是宿主机的
- 网络：默认是bridge，那是内部的
- 硬盘：内部 + 挂载部分

**Comment by jaychoubaby** [comment]
> 

好的 那我先挂载再测试看看，另外两个issues是否也都是因为我没有挂载部署导致的啊

**Comment by jaychoubaby** [comment]
> 

想了一下 如果挂载启动的话，只监测宿主机某个路径好像意义也不大

**Comment by jaychoubaby** [comment]
> 需要 docker 内执行，因为 docker 内外的环境不同。
> 
> 
> 
> 如果要监控 docker 宿主机的某个路径，要么挂载到 docker，要么直接在宿主机运行 sbm

请问是要挂在在哪个路径呢 /proc 吗
